export default{
    // 分享文案
	share: {
		title: '前途未卜？',
		desc: '现在是变化的我们，也是不变的我们。',
		link: location.href.split('#')[0],
		imgUrl: 'http://hz.cdn.24.friendia.net/poster/static/share2.png',
	},
	imgs: [
		'imgs/bg-effect-1.png',
		'imgs/bg-effect-2.png',
		'imgs/bg-effect-3.png',
		'imgs/bg-effect-4.png',
		'imgs/bg-effect-5.png',
		'imgs/bg-effect-6.png',
		'imgs/bg-effect-7.png',
		'imgs/bg-effect-8.png',
		'imgs/bg-effect-9.png',
		'imgs/bg-frame-1.png',
		'imgs/bg-frame-2.png',
		'imgs/bg-frame-3.png',
		'imgs/bg-frame-4.png',
		'imgs/bg-frame-5.png',
		'imgs/bg-frame-6.png',
		'imgs/bg-frame-7.png',
		'imgs/bg-frame-8.png',
		'imgs/bg-frame-9.png',
		'imgs/bg-frame-effect-1.png',
		'imgs/bg-frame-effect-2.png',
		'imgs/bg-frame-effect-3.png',
		'imgs/bg-frame-effect-4.png',
		'imgs/bg-frame-effect-5.png',
		'imgs/bg-frame-effect-6.png',
		'imgs/bg-frame-effect-7.png',
		'imgs/bg-frame-effect-8.png',
		'imgs/bg-frame-effect-9.png',
		'imgs/bg-logo.png',
		'imgs/bg-logo-50.png',
		'imgs/bg-logo-black.png',
		'imgs/bg-logo-gold.png',
		'imgs/bg-logo-large.png',
		'imgs/bg-main.png',
		'imgs/bg-progress-gray.png',
		'imgs/bg-progress-white.png',
		'imgs/bg-qrcode.png',
		'imgs/btn-up.png',
		'imgs/icon-up.png',
		'imgs/text-0-many.png',
		'imgs/text-0-mention.png',
		'imgs/text-0-needguid.png',
		'imgs/text-0-newworld.png',
		'imgs/text-0-noname.png',
		'imgs/text-1.1.png',
		'imgs/text-1-change.png',
		'imgs/text-1-discover.png',
		'imgs/text-1-value.png',
		'imgs/text-2.1.png',
		'imgs/text-2.2.png',
		'imgs/text-2-fearless.png',
		'imgs/text-2-landscape.png',
		'imgs/text-2-longway.png',
		'imgs/text-2-sun.png',
		'imgs/text-3.1.png',
		'imgs/text-4.1.png',
		'imgs/text-change.png',
		'imgs/name/bg-fandeng.png',
		'imgs/name/bg-gudian.png',
		'imgs/name/bg-liangzhanhua.png',
		'imgs/name/bg-libeika.png',
		'imgs/name/bg-linan.png',
		'imgs/name/bg-linshao.png',
		'imgs/name/bg-me.png',
		'imgs/name/bg-panyao.png',
		'imgs/name/bg-papi.png',
		'imgs/name/bg-qinshuo.png',
		'imgs/name/bg-songchao.png',
		'imgs/name/bg-tanjing.png',
		'imgs/name/bg-xuzhibin.png',
		'imgs/name/bg-yangdazhi.png',
		'imgs/name/bg-yuminhong.png',
		'imgs/name/bg-zhangmofan.png',
	],
	audios: {
		bgm: {
			src: 'audios/bgm.mp3',
			loop: true,
		},
	},
};
